name: "Pull Request Workflow"

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited, synchronize]

jobs:
  claude-review:
    uses: sakshi-devotess/github-action/.github/workflows/claude-review.yml@main
    secrets:
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
